/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormItem: typeof import('./components/form/FormItem.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputDebounce: typeof import('./components/form/InputDebounce.vue')['default']
    ListNone: typeof import('./components/list/ListNone.vue')['default']
    ListScroll: typeof import('./components/list/ListScroll.vue')['default']
    PlayVideo: typeof import('./components/play/PlayVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VanNavBar: typeof import('vant/es')['NavBar']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
